networks:
  amard_network:
    driver: bridge
volumes:
  pgadmin_data:
    driver: local
  postgres_data:
    driver: local
  minio_data:
    driver: local
  

services:
  ess.api:
    container_name: API
    image: ${DOCKER_REGISTRY-}essapi
    build:
      context: .
      dockerfile: src/ESS.Api/Dockerfile
    ports:
      - "${API_HTTP_PORT}:8080"
      - "${API_HTTPS_PORT}:8081"
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://ess.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ess.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ConnectionStrings__DatabaseConnectionString=${CONNECTIONSTRINGS__DATABASECONNECTIONSTRING}
      - ConnectionStrings__IafDatabaseConnectionString=${CONNECTIONSTRINGS__IAFDATABASECONNECTIONSTRING}
      #JWT
      - Jwt__Key=${JWT__KEY}
      - Jwt__Issuer=${JWT__ISSUER}
      - Jwt__Audience=${JWT__AUDIENCE}
      - Jwt__ExpirationInMinutes=${JWT__EXPIRATIONINMINUTES}
      - Jwt__RefreshTokenExpirationDays=${JWT__REFRESHTOKENEXPIRATIONDAYS}
      #SeedAdmin 
      - SeedAdmin__PhoneNumber=${SEEDADMIN__PHONENUMBER}
      - SeedAdmin__Password=${SEEDADMIN__PASSWORD}
      - SeedAdmin__NationalCode=${SEEDADMIN__NATIONALCODE}
      - SeedAdmin__Name=${SEEDADMIN__NAME}
      #EncryptionKey
      - Encryption__Key=${ENCRYPTION__KEY}
      #- DOTNET_RUNNING_IN_CONTAINER=true
      #Kestrel
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://+:8081
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/certs/esscert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
      # CORS
      - Cors__AllowedOrigins__0=${CORS__ALLOWEDORIGINS__0}
      - Cors__AllowedOrigins__1=${CORS__ALLOWEDORIGINS__1}
      - Cors__AllowedOrigins__2=${CORS__ALLOWEDORIGINS__2}
      - Cors__AllowedOrigins__3=${CORS__ALLOWEDORIGINS__3}
      - Cors__AllowedOrigins__4=${CORS__ALLOWEDORIGINS__4}
      - Cors__AllowedOrigins__5=${CORS__ALLOWEDORIGINS__5}
      # MinIo
      - MinIO__Endpoint=MinioStorage:${MINIO_API_PORT}
      - MinIO__AccessKey=${MINIO_ACCESS_KEY}
      - MinIO__SecretKey=${MINIO_SECRET_KEY}
      - MinIO__BucketName=${MINIO_BUCKET_NAME}
      - MinIO__UseSSL=${MINIO_USE_SSL}
      #MelliPayamak
      - MelliPayamak__Username=${MELLIPAYAMAK_USERNAME}
      - MelliPayamak__Password=${MELLIPAYAMAK_PASSWORD}
      - MelliPayamak__FromNumber=${MELLIPAYAMAK_FROM_NUMBER}
      - MelliPayamak__ApiUrl=${MELLIPAYAMAK_API_URL}
      - MelliPayamak__VerificationTemplate=${MELLIPAYAMAK_VERIFICATION_TEMPLATE}
    volumes:
      - ${REPORTS_PAYMENT}:/app/reports/payment:ro
      - ${REPORTS_PERSONNEL}:/app/reports/personnel-file:ro
      - ${CERT_FILE}:/certs/esscert.pfx:ro
    depends_on:
      - ess.postgres
      - ess.minio
    networks:
      - amard_network


  ess.postgres:
    container_name: PostgresDatabase
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - amard_network
    restart: unless-stopped

  ess.pgadmin:
    container_name: PgAdmin
    image: elestio/pgadmin:REL-9_8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - ess.postgres
    networks:
      - amard_network

  ess.seq:
    container_name: SeqLogging
    image: datalust/seq:2025.2
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - "${SEQ_PORT_HTTP}:80"
      - "${SEQ_PORT_INGEST}:5341"
    networks:
      - amard_network

  ess.aspire-dashboard:
    container_name: AspireDashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - "${DASHBOARD_PORT}:18888"
    networks:
      - amard_network

  ess.minio:
    container_name: MinioStorage
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
        MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
        MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
    - "${MINIO_API_PORT}:9000"
    - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    # - ${MINIO_CERT_PUBLIC}:/root/.minio/certs/public.crt:ro
    # - ${MINIO_CERT_PRIVATE}:/root/.minio/certs/private.key:ro
    networks:
    - amard_network
    restart: unless-stopped
 
  ess.client:
    container_name: ClientUI
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - ess.api
    networks:
      - amard_network


