networks:
  amard_network:
    driver: bridge

services:
  ess.api:
    container_name: API
    image: ${DOCKER_REGISTRY-}essapi
    build:
      context: .
      dockerfile: src/ESS.Api/Dockerfile
    ports:
      - "${API_HTTP_PORT}:8080"
      - "${API_HTTPS_PORT}:8081"
    environment:
      # Seq
      # - OTEL_EXPORTER_OTLP_ENDPOINT=http://ess.seq:5341/ingest/otlp
      # - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      # Aspire Dashboard
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://ess.aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ConnectionStrings__DatabaseConnectionString=${CONNECTIONSTRINGS__DATABASECONNECTIONSTRING}
      - ConnectionStrings__IafDatabaseConnectionString=${CONNECTIONSTRINGS__IAFDATABASECONNECTIONSTRING}
      - Jwt__Key=${JWT__KEY}
      - Jwt__Issuer=${JWT__ISSUER}
      - Jwt__Audiance=${JWT__AUDIANCE}
      - Jwt__ExpirationInMinutes=${JWT__EXPIRATIONINMINUTES}
      - Jwt__RefreshTokenExpirationDays=${JWT__REFRESHTOKENEXPIRATIONDAYS}
      - SeedAdmin__PhoneNumber=${SEEDADMIN__PHONENUMBER}
      - SeedAdmin__Password=${SEEDADMIN__PASSWORD}
      - SeedAdmin__NationalCode=${SEEDADMIN__NATIONALCODE}
      - SeedAdmin__Name=${SEEDADMIN__NAME}
      - Encryption__Key=${ENCRYPTION__KEY}
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=https://+:8081
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Path=/certs/esscert.pfx
      - ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password=${CERT_PASSWORD}
      # CORS
      - Cors__AllowedOrigins__0=${CORS__ALLOWEDORIGINS__0}
      - Cors__AllowedOrigins__1=${CORS__ALLOWEDORIGINS__1}
      - Cors__AllowedOrigins__2=${CORS__ALLOWEDORIGINS__2}
      - Cors__AllowedOrigins__3=${CORS__ALLOWEDORIGINS__3}
      - Cors__AllowedOrigins__4=${CORS__ALLOWEDORIGINS__4}
      - Cors__AllowedOrigins__5=${CORS__ALLOWEDORIGINS__5}
    volumes:
      - ${REPORTS_PAYMENT}:/app/reports/payment
      - ${REPORTS_PERSONNEL}:/app/reports/personnel-file
      - ${CERT_FILE}:/certs/esscert.pfx:ro
    depends_on:
      - ess.postgres
    networks:
      - amard_network


  ess.postgres:
    container_name: PostgresDatabase
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./.containers/postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - amard_network

  ess.pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./.containers/pgadmin_data:/var/lib/pgadmin
    depends_on:
      - ess.postgres
    networks:
      - amard_network

  ess.seq:
    container_name: SeqLogging
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./.containers/seq_data:/data
    ports:
      - "${SEQ_PORT_HTTP}:80"
      - "${SEQ_PORT_INGEST}:5341"
    networks:
      - amard_network

  ess.aspire-dashboard:
    container_name: AspireDashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.3
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - "${DASHBOARD_PORT}:18888"
    networks:
      - amard_network
